[client]
showSidebarNavigation = false
toolbarMode = "auto" # auto developer viewer minimal

[theme]
base = "dark"
primaryColor = "#F63366"
backgroundColor = "black"
secondaryBackgroundColor = "purple"
font = "monospace"

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "localhost"
