[client]
showSidebarNavigation = false
toolbarMode = "auto" # auto developer viewer minimal

[theme]
base = "light"
primaryColor = "#6C3DE8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0EBFC"
textColor = "#1A1A2E"
font = "sans serif"

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "localhost"
