[client]
showSidebarNavigation = false
toolbarMode = "auto" # auto developer viewer minimal

[theme]
base = "light"
primaryColor = "#A69EB0"
backgroundColor = "#FFFFFF"
textColor = "black"
secondaryBackgroundColor = "#DADAE3"
font = "monospace"

[browser]
gatherUsageStats = false
serverPort = 8501
serverAddress = "localhost"
